version: "3.8"

services:
  express:
    build:
      context: .
      dockerfile: single-stage.dockerfile

    ports:
      - "8080"

    deploy:
      replicas: 4

    restart: always

    environment:
      - PORT=8080

    networks:
      - front-network

  proxy:
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    ports:
      - 8081:80

    depends_on:
      - express

    networks:
      - front-network

networks:
  front-network:
    driver: bridge
